# Generated by Django 4.2 on 2023-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discord_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='locale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='public_flags',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
