# Generated by Django 4.2 on 2023-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_alter_discorduser_discord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
