# Generated by Django 4.2 on 2023-06-03 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_alter_discorduser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
