# Generated by Django 4.2 on 2023-05-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='deleted_at',
        ),
    ]
